name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: Prepare connectivity
        run: sudo modprobe ifb numifbs=1
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --cap-add=NET_ADMIN -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.1.1 https://www.sitespeed.io  -n 3 --browsertime.connectivity.engine throttle -c cable 
